### ISSUE TITLE
Invalid group when creating redirect

### ISSUE THREAD

**Issue by virtualLast** [johngodley/redirection#126]
Hey Guys,

This ticket is a continuation of a support request I launched
[See original support request](https://wordpress.org/support/topic/invalid-group-when-creating-redirect-2?replies=10#post-8629903)

When trying to create new redirects, I am unable because I cannot select the correct group. There are no groups available for me to select and I cannot create new groups. 

Current version if 2.4.5, I have older versions installed on other sites and they are still working fine, even with the latest version of Wordpress

**Comment by ekazda** [comment]
This is an issue related to importing. Imported CSV files do not import properly because the groups that used to be automatically generated do not exist in newer versions of the plugin.

**Comment by ekazda** [comment]
Please review line 97 of the models/database.php file. I think the error may have something to do with the recent change to the IF statement.

**Comment by johngodley** [comment]
This should be fixed

**Comment by Dickurt** [comment]
Still having this issue on Wordpress 4.7.1.

When the plugin is activated, the default groups ("Redirections" and "Modified Posts") aren't created. And when I try to create a new group, I get a message saying "Give a name for the group", even though I entered a name for it.

Might have something to do with permissions.

**Comment by volmerf** [comment]
I'm having the same problem as well as many other problems reading the review section of this plugin. Is this plugin still being updated?

**Comment by kLOsk** [comment]
@volmerf & @Dickurt I was able to solve this problem by uninstalling and reinstalling the plugin. This should trigger the table creation.
