### ISSUE TITLE
error after update, can not acces plugin

### ISSUE THREAD

**Issue by johncarrier** [johngodley/redirection#1664]
Plugin: 4.2.2
WordPress: 5.1.1 (single)
PHP: 7.0.33
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
JavaScript: https://terapeutiskgravidmassage.se/wp-content/plugins/redirection/redirection.js
REST API: https://terapeutiskgravidmassage.se/wp-json/
Buster: 4.2.2 === 4.2.2

TypeError: e[n] is undefined

    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in div
    in t
    in Connect(t)
    in t
    in Unknown

**Comment by johngodley** [comment]
Would it be possible to [see this in action](https://redirection.me/contact/)?

**Comment by johncarrier** [comment]
Hi see attached

Do you need log in?

 

Med vänliga hälsningar 

John Carrier

 

Behandlingsteam John Carrier

Nybrogatan 71
114 40 Stockholm
Telefon: +46(0)8 – 12 14 40 30

Web:  www.gravidmassage.se

Web: www.behandlingsteamjohncarrier.se

 

 

Från: John [mailto:notifications@github.com] 
Skickat: den 14 april 2019 16:50
Till: johngodley/redirection
Kopia: johncarrier; Author
Ämne: Re: [johngodley/redirection] error after update, can not acces plugin (#1664)

 

Would it be possible to see this in action <https://redirection.me/contact/> ?

**Comment by johngodley** [comment]
I don't think attachments make it through email on Github. But yes, if it's possible to login and see this in action I should be able to track down the cause of it pretty quickly. If that is possible then please contact me at  https://redirection.me/contact/

**Comment by johncarrier** [comment]
Done, thx!

 

Med vänliga hälsningar 

John Carrier

 

Behandlingsteam John Carrier

Nybrogatan 71
114 40 Stockholm
Telefon: +46(0)8 – 12 14 40 30

Web:  www.gravidmassage.se

Web: www.behandlingsteamjohncarrier.se

 

 

Från: John [mailto:notifications@github.com] 
Skickat: den 14 april 2019 20:09
Till: johngodley/redirection
Kopia: johncarrier; Author
Ämne: Re: [johngodley/redirection] error after update, can not acces plugin (#1664)

 

I don't think attachments make it through email on Github. But yes, if it's possible to login and see this in action I should be able to track down the cause of it pretty quickly. If that is possible then please contact me at https://redirection.me/contact/

**Comment by johngodley** [comment]
Thanks. With that I was able to reproduce the problem and it should be fixed in 4.2.3

**Comment by johncarrier** [comment]
Hi still not working

See 

 

Med vänliga hälsningar 

John Carrier

 

Behandlingsteam John Carrier

Nybrogatan 71
114 40 Stockholm
Telefon: +46(0)8 – 12 14 40 30

Web:  www.gravidmassage.se

Web: www.behandlingsteamjohncarrier.se

 

 

Från: John [mailto:notifications@github.com] 
Skickat: den 16 april 2019 09:11
Till: johngodley/redirection
Kopia: johncarrier; Author
Ämne: Re: [johngodley/redirection] error after update, can not acces plugin (#1664)

 

Thanks. With that I was able to reproduce the problem and it should be fixed in 4.2.3

**Comment by johngodley** [comment]
The above bug is fixed on your site. What you are seeing is a warning message stating that your REST API is not working. This is because your server is rejecting:

`content-type: application/json; charset=utf-8`

This is a separate issue and is caused by something on your server, possibly a firewall or server configuration.
