### ISSUE TITLE
Import CSV with regex

### ISSUE THREAD

**Issue by KimchaC** [johngodley/redirection#185]
Hi,

I needed to import a CSS with regex redirects such as this one:
source: ^\/about-us\/terms-of-use(\/)?(\?.*)?$
target: /terms-of-use/$2

To redirect URLS such as
- whatever.com/about-us/terms-of-use/
- whatever.com/about-us/terms-of-use/
- whatever.com/about-us/terms-of-use/?utm_source=...
- whatever.com/about-us/terms-of-use?utm_source=...

Unfortunately the import process stripped the escaped slashed and turned the rules into "^/about-us/terms-of-use(/)?(?.*)?$".

I was able to temporarily fix it, by commenting out /models/redirect.php line 148:
`//		$details = array_map( 'stripslashes', $details );`

Perhaps the slashes could be stripped only if it is not an import or only if regex is false?

Greetings, Kim

**Comment by johngodley** [comment]
Should be fixed in 2.6

**Comment by omacranger** [comment]
I'm still having this issue when trying to import a CSV with escaping slashes being stripped using version 2.6.3 and the 'regex' column being set to `1`.
