### ISSUE TITLE
Importing CSV File generating false Status code in Plugin

### ISSUE THREAD

**Issue by maamirh** [johngodley/redirection#3405]
I have 1K+ faulty URLs on my site and I need to set status code 410. By adding manually in the plugin it's creating no issue but when I am importing CSV file in the plugin then its creates status code 301 instead of 410. Kindly have a look at the column format.

https://docs.google.com/spreadsheets/d/1UJypULdkmV96Nh0QFMK4lo6NzS8R_3hEGn8KAZWU7a0/edit?usp=sharing

**Comment by johngodley** [comment]
The format is shown here:

https://redirection.me/support/import-export-redirects/

You have the code column in the wrong place

**Comment by maamirh** [comment]
First I add 1 URL in Plugin and then export the CSV file in that file, I added my all URLs in that file which I did export. Can you correct the file format? I added the sheet link above.

**Comment by johngodley** [comment]
What version of the plugin are you using?

**Comment by maamirh** [comment]
V 6.0.2

**Comment by johngodley** [comment]
That is the WordPress version. What version of the plugin?

**Comment by maamirh** [comment]
Version 5.3.2 

I did export the file from plugin to obtain file format.Now plugin is showing update .

**Comment by johngodley** [comment]
Yes, because that problem has been fixed

**Comment by maamirh** [comment]
This is not solved yet i think .I am sharing Plugin screenshot and csv file screenshot .
![image](https://user-images.githubusercontent.com/46965638/188894592-ff5c9ec3-0229-4b42-b494-7418770b7bf9.png)
![image](https://user-images.githubusercontent.com/46965638/188894681-b061193d-6b09-44a6-9bae-a0205dd7b12f.png)

**Comment by maamirh** [comment]
I keep the column TARGET empty too and try again but still, 301 code is generating after file import in the plugin. You can see the screenshot fo csv file format in the above comment.

**Comment by johngodley** [comment]
Ok, you will need to wait until it is fixed.

**Comment by johngodley** [comment]
This should now be fixed.
