### ISSUE TITLE
RSS feed not working

### ISSUE THREAD

**Issue by AaronTacke** [johngodley/redirection#3971]
Hey, thanks for the great work, I'm currently facing a problem with the RSS feature:

The URL for me is https://mysite.com/wp-admin/tools.php?page=redirection.php&sub=rss&module=1&token=xyz, but when adding this as a WP RSS Block it returns
```
RSS Error: A feed could not be found at `https://mysite.com/wp-admin/tools.php?page=redirection.php&sub=rss&module=1&token=xyz`; the status code is `200` and content-type is `text/html; charset=UTF-8
```

And `https://www.rssboard.org/rss-validator/` says
It looks like this is a web page, not a feed. I looked for a feed associated with this page, but couldn't find one. Please enter the address of your feed to validate.

I'm using WordPress 6.7.1 and PHP 8.1.

**Comment by johngodley** [comment]
The RSS feed should now be working

**Comment by ejnwebmaster** [comment]
Just noting that I have the same issue still.

I'm using Version 5.7.3.

**Comment by johngodley** [comment]
> Just noting that I have the same issue still.

It is not the same issue. The one here was the feed wasn't working at all. The one you reported is that it is breaking your feed reader.
