### ISSUE TITLE
Export just reloads list

### ISSUE THREAD

**Issue by tomsterritt** [johngodley/redirection#67]
Going to the Modules tab and selecting "CSV" (or any of them for that matter) just takes you back to the Redirects list.

**Comment by jerundle** [comment]
I have this issue as well. 2.4.4 Would love an update.

**Comment by johngodley** [comment]
This should have been fixed for a while now, so closing

**Comment by rootion** [comment]
Using WP 4.7.5 and Redirection 2.6, this issue is still happening.
Select CSV with modules or no modules list just refreshes the page and nothing is downloaded.
Tried with Chrome and Firefox.
