### ISSUE TITLE
Admin screen throws error message

### ISSUE THREAD

**Issue by intermonkey** [johngodley/redirection#675]
When visiting any of the wp-admin screens, I get the following message:

**Something went wrong 🙁**

> Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.
> 
> If that doesn't help, open your browser's error console and create a new issue with the details.
> 
> Please mention log, and explain what you were doing at the time

`Plugin: 3.0.1
WordPress: 4.9.2
PHP: 5.5.34-1+deb.sury.org~precise+1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Buster: 3.0.1 === 3.0.1
TypeError: e.request is undefined`

In my browser inspector, I see:
Chrome:
```
Mixed Content: The page at 'https://DOMAINNAME.com/wp-admin/tools.php?page=redirection.php&sub=log&debug=' was loaded over HTTPS, but requested an insecure resource 'http://DOMAINNAME.com/wp-json/redirection/v1/log/?per_page=50'. This request has been blocked; the content must be served over HTTPS.
tools.php?page=redirection.php&sub=log&debug=:1 

Fetch API cannot load https://DOMAINNAME.com/wp-json/redirection/v1/log?per_page=50. Redirect failed.
tools.php?page=redirection.php&sub=log&debug=:1
```

Firefox:
`Blocked loading mixed active content “http://domain.com/wp-json/redirection/v1/log/?per_page=50”    [Learn More]     tools.php`

I tried the Beta (v3.1) but that didn't fix it.

As far as I can tell, my redirects are still working but I obviously can't manage them now.

### Environment

MacOS 10.13.2
WordPress 4.9.2
Chrome Version 63.0.3239.132
FireFox 58.0 (64-bit)
Safari Version 11.0.2
Redirection Version 3.0.1

**Comment by johngodley** [comment]
This problem looks different to the one I tried to tackle in 3.1.

Do you know where the `&debug=:1` comes from in the URL? That doesn't exist in the plugin so it's a bit puzzling.

For the other problem it looks like you are on a https site, and it is trying to load data from a http site. If you go to the Support page in Redirection and look at the 'WordPress REST API' section does it say it is loading from a http URL?

Also, if you look in Settings > General > WordPress/Site Address - are they http or https?

**Comment by intermonkey** [comment]
1. I think that `&debug=:1` was from something I was trying. I removed it, refreshed and here's what I'm getting in Chrome:

```
Mixed Content: The page at 'https://DOMAIN.com/wp-admin/tools.php?page=redirection.php' was loaded over HTTPS, but requested an insecure resource 'http://DOMAIN.com/wp-json/redirection/v1/redirect/?orderby=id&per_page=50'. This request has been blocked; the content must be served over HTTPS.
tools.php?page=redirection.php:1 

Fetch API cannot load https://DOMAIN.com/wp-json/redirection/v1/redirect?orderby=id&per_page=50. Redirect failed.
tools.php?page=redirection.php:1 

Mixed Content: The page at 'https://DOMAIN.com/wp-admin/tools.php?page=redirection.php' was loaded over HTTPS, but requested an insecure resource 'http://DOMAIN.com/wp-json/redirection/v1/group/?per_page=50'. This request has been blocked; the content must be served over HTTPS.
tools.php?page=redirection.php:1 

Fetch API cannot load https://DOMAIN.com/wp-json/redirection/v1/group?per_page=50. Redirect failed.
tools.php?page=redirection.php:1 
```

2. The Support page throws the same error message. I can't get to any Redirection admin pages at all.

3. Settings > General > WordPress/Site Address = both are https

UPDATE: I temporarily fixed this on my production site by downgrading to Redirection v2.10.1
My testing site still has 3.0.1 and still throws the error.

**Comment by johngodley** [comment]
I've released version 3.1 which I think should help with this. Let me know how it goes

**Comment by intermonkey** [comment]
Still getting the same 'Mixed content' errors. But with this version, I can now see Plugin Status.

```
WordPress REST API | Problem REST API returns an error code (401 - https://DOMAIN.com/wp-json/)
Redirection routes | Problem REST API is not working so routes not checked
```

**Comment by johngodley** [comment]
Sorry for the delay in replying. I've been trying to track this problem down but so far it's escaped me. I have released 3.2 where you can select different options for the REST API which will probably allow this problem to be fixed.

I'd love to be able to fix it properly it though. If you have it on a site that I can look at I'd like to do that and see what the underlying problem is.

**Comment by johngodley** [comment]
Closing for now, please reopen with more information

**Comment by intermonkey** [comment]
The recent update seems to have fixed it! No more error messages! Thanks for all your speedy support!
