### ISSUE TITLE
options/settings page.  TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by helpgood** [johngodley/redirection#678]
To help track problems please follow this template. If you can provide screenshots then that will help.

*Please replace this template with your own details!*

### Summary

It seems that there's still https:// issue on the latest version.

### Actual Behavior

Something went wrong 🙁
Redirection is not working. Try clearing your browser cache and reloading this page.  If you are using a page caching plugin or service (CloudFlare, OVH, etc) then you can also try clearing that cache.

If that doesn't help, open your browser's error console and create a new issue with the details.

Please mention options, and explain what you were doing at the time

### Steps to reproduce

Go to the plugin setting page.

### Environment

Plugin: 3.0.1
WordPress: 4.9.2
PHP: 7.0.25-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Buster: 3.0.1 === 3.0.1
TypeError: Cannot read property 'status' of undefined

Chrome inspector error:
--------------------
Mixed Content: The page at 'https://www.example.org/wp-admin/tools.php?page=redirection.php&sub=options' was loaded over HTTPS, but requested an insecure resource 'http://www.example.org/wp-json/redirection/v1/setting/'. This request has been blocked; the content must be served over HTTPS.
tools.php?page=redirection.php&sub=options:1 

Fetch API cannot load https://www.example.org/wp-json/redirection/v1/setting. Redirect failed.

**Comment by johngodley** [comment]
If you go to the WordPress menu Settings > General is the URL for your Site/WordPress URL http or https?

<img width="594" alt="2018-01-26_09-30-37" src="https://user-images.githubusercontent.com/1277682/35433514-968738c4-027b-11e8-853f-bd636eefcfaa.png">

**Comment by svandragt** [comment]
We have this exact error (TypeError: Cannot read property 'status' of undefined), and we use run this on multisite with a domain mapper. The previous release worked ok.

**Comment by helpgood** [comment]
@johngodley,
Both were already htpps.

WordPress Address (URL) |  https://www.test.org
Site Address (URL) |  https://www.test.org

**Comment by johngodley** [comment]
@svandragt I think that is a different problem, and it could be fixed in the 3.1 beta:

https://github.com/johngodley/redirection/releases/tag/3.1

@helpgood are you also using multisite by any chance? Does the request for https://www.example.org/wp-json/ show some data?

**Comment by helpgood** [comment]
@johngodley,
Single site only.
I can't see the data easily, sorry.

**Comment by helpgood** [comment]
@johngodley 
If it helps, the previous version we use before Upgrading the plugin was Version 2.10.1, and that worked with no problem.

**Comment by johngodley** [comment]
I've released version 3.1 which may help. Let me know how it goes

**Comment by helpgood** [comment]
@johngodley 
Unfortunately, it still doesn't work.  Pretty much the same error.
---
Plugin: 3.1
WordPress: 4.9.2 (single)
PHP: 7.0.25-1+ubuntu16.04.1+deb.sury.org+1
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
REST API: https://www.nextforautism.org/wp-json/

Error: Failed to fetch
-------------


Something went wrong 🙁
Failed to fetch

Please take a look at the plugin status. It may be able to identify and "magic fix" the problem.
Redirection is unable to talk to your REST API. If you have disabled it then you will need to enable it.
Security software may be blocking Redirection. You will need to configure this to allow REST API requests.
Caching software, in particular Cloudflare, can cache the wrong thing. Try clearing all your caches.
Please temporarily disable other plugins! This fixes so many problems.

----------

Mixed Content: The page at 'https://www.example.org/wp-admin/tools.php?page=redirection.php' was loaded over HTTPS, but requested an insecure resource 'http://www.example.org/wp-json/redirection/v1/redirect/?orderby=id&_wpnonce=decae8e1bc'. This request has been blocked; the content must be served over HTTPS.
tools.php?page=redirection.php:1 

Fetch API cannot load https://www.example.org/wp-json/redirection/v1/redirect?orderby=id&_wpnonce=decae8e1bc. Redirect failed.
tools.php?page=redirection.php:1 

Mixed Content: The page at 'https://www.example.org/wp-admin/tools.php?page=redirection.php' was loaded over HTTPS, but requested an insecure resource 'http://www.example.org/wp-json/redirection/v1/group/?_wpnonce=decae8e1bc'. This request has been blocked; the content must be served over HTTPS.
tools.php?page=redirection.php:1 

Fetch API cannot load https://www.example.org/wp-json/redirection/v1/group?_wpnonce=decae8e1bc. Redirect failed.
tools.php:511 WOP Array(1)

**Comment by johngodley** [comment]
I think version 3.2 beta should fix the 'failed to fetch' error. This is, I think, caused by your site redirecting requests. If you try 3.2 beta you may need to visit the plugin's 'support' page and maybe press the 'magic fix' button if it suggests you do so.

https://github.com/johngodley/redirection/releases/tag/3.2-beta

The mixed content warnings I don't know about. They may be related, but if they aren't would it be possible to get a login to the site and try and debug things? If that's ok I can be contacted from https://redirection.me/contact/

**Comment by johngodley** [comment]
Closing for now, please reopen with more details
